### ISSUE TITLE
Spotify install error

### ISSUE THREAD

**Issue by Vitorvlv** [solus-project/3rd-party#264]
Installing spotify either with the software center or [following these instrutions leads](https://solus-project.com/articles/software/third-party/en/) to an error:

Could not fetch destination file "https://www.solus-project.com/source/spotify-client_1.0.67.582.g19436fa3-28_amd64.deb": [Errno 14] HTTPS Error 404 - Not Found

**Comment by aszrul** [comment]
You need to try install Spotify multiple times by using those command lines. All that I can say is it is a very weird bug. I tried downloaded the source .deb directly from the Spotify official repository and it was perfectly fine (usually fine but sometimes ...), but by using those Solus command lines hang the download multiple times. Although the other packages such as Google Chrome, Adobe Flash Player for Firefox and Android Studio were usually perfectly fine for the installation. At first I thought it was my internet connection suddenly drop because of peak hours but then I did tried install the Spotify during non peak hours, unfortunately the results were same as peak hours.

I guess the culprit was the Spotify server itself because when I tried install the Spotify on my Windows 10 machine, the download process during installation was suddenly hang/interrupted in the middle. It was success after I tried it multiple times.

**Comment by karlisk** [comment]
Trying out Solus OS and ran into this problem as well. From what I'm to understand, this repo is Deprecated and in the process of being migrated. In the meantime I fiddled around a bit and got it working, here's what I did:

(OPTIONAL - do wherever you want it to, just be aware in my following description I'm assuming everything necessary is downloaded to the same directory you are currently in) Move to a directory where you can work or make a new one:
`mkdir /tmp/spotify && cd /tmp/spotify`

1st: download the eopkg info
```
wget https://raw.githubusercontent.com/solus-project/3rd-party/master/multimedia/music/spotify/pspec.xml
wget raw.githubusercontent.com/solus-project/3rd-party/master/multimedia/music/spotify/actions.py
```

2nd: download the correct Spotify *.deb from [http://repository-origin.spotify.com/pool/non-free/s/spotify-client/](http://repository-origin.spotify.com/pool/non-free/s/spotify-client/) and calculate the SHA1SUM (I didn't know how else to do this without downloading). In my case, I used the latest available x86_64 version: 'spotify-client_1.0.69.336.g7edcc575-39_amd64.deb'
```
wget http://repository-origin.spotify.com/pool/non-free/s/spotify-client/spotify-client_1.0.69.336.g7edcc575-39_amd64.deb
sha1sum potify-client_1.0.69.336.g7edcc575-39_amd64.deb
```

3rd: Modify the eopkg info to correspond to the version you want to install (including the SHA1SUM)
Specifically, edit the 'pspec.xml' and replace:
`<Archive sha1sum="28e7ebde9419d07b1556a022917c3201acfb7fd1" type="binary">http://repository-origin.spotify.com/pool/non-free/s/spotify-client/spotify-client_1.0.69.336.g7edcc575-39_amd64.deb</Archive>`

With:
`<Archive sha1sum="28e7ebde9419d07b1556a022917c3201acfb7fd1" type="binary">http://repository-origin.spotify.com/pool/non-free/s/spotify-client/spotify-client_1.0.69.336.g7edcc575-39_amd64.deb</Archive> `

Also, in the same xml, add the new version to the versions list below:
```
<Update release="38">
	<Date>12-14-2017</Date>
	<Version>1.0.69.336</Version>
	<Comment>Update to 1.0.69.336</Comment>
	<Name>Name Surname</Name>
	<Email>none</Email>
</Update>
```

So that it looks something like this (a snippet from my xml):
```
    <History>
        <Update release="38">
            <Date>12-14-2017</Date>
            <Version>1.0.69.336</Version>
            <Comment>Update to 1.0.69.336</Comment>
            <Name>Karlis K.</Name>
            <Email>karlis.kavacis@protonmail.com</Email>
        </Update>

        <Update release="37">
            <Date>11-22-2017</Date>
            <Version>1.0.67.582</Version>
            <Comment>Update to 1.0.67.582</Comment>
            <Name>Peter O'Connor</Name>
            <Email>peter@solus-project.com</Email>
        </Update>
```

4th: Generate the eopkg
`sudo eopkg bi --ignore-safety pspec.xml`

5th: if there were no errors in step 4, install the newly generated package
`sudo eopkg install spotify-*.eopkg`

**Comment by ahahn94** [comment]
The spotify update broke the package. This is completely normal . I will create a pull request wtih the required changes. Good work, @karlisk.

**Comment by andrewcodes** [comment]
I just tried installing Spotify again via: 
```
sudo eopkg bi --ignore-safety https://raw.githubusercontent.com/solus-project/3rd-party/master/multimedia/music/spotify/pspec.xml
```
but I'm getting an error:
```
> sudo eopkg bi --ignore-safety https://raw.githubusercontent.com/solus-project/3rd-party/master/multimedia/music/spotify/pspec.xml
pspec.xml                      (11.0 KB)100%     32.65 MB/s [00:00:00] [complete]
actions.py                     (490.0  B)100%      6.24 MB/s [00:00:00] [complete]
DEBUG: InstallDB initialized in 0.00515794754028.
DEBUG: RepoDB initialized in 0.000159025192261.
DEBUG: Remote file can not be reached. Previously downloaded part of the file will be removed.
Building source package: spotify
component.xml                  (48.0  B)100%    881.65 KB/s [00:00:00] [complete]
Fetching source from: http://repository-origin.spotify.com/pool/non-free/s/spotify-client/spotify-client_1.0.69.336.g7edcc575-39_amd64.deb
spotify-client_1.0.69.336.g7edcc575-39_amd64.deb (1.0 KB)100%     26.04 MB/s [00:00:00] [complete]
Source archive is stored: /var/cache/eopkg/archives/spotify-client_1.0.69.336.g7edcc575-39_amd64.deb
Unpacking archive(s)...
Program terminated.
unpack: check_file_hash failed
Please use 'eopkg help' for general help.
```

**Comment by karlisk** [comment]
This is certainly odd:
`unpack: check_file_hash failed`

**Comment by karlisk** [comment]
@andrewcodes think you could do:
```
rm -rf /var/cache/eopkg/archives/spotify*
rm -rf /etc/eopkg/spotify*
```
and try installing again? Perhaps the SHA1SUM check failed because the setup was loading old cached files?

**Comment by JoshStrobl** [comment]
Can confirm that the sha is correct. Please clear your cache and make sure it's not attempting to use any previous failed downloaded files.

**Comment by karlisk** [comment]
Had to do a fresh install (borked my install by fiddling with grub, mountpoints and partitions too much) of Solus, just did a Spotify install according to the normal procedures as detailed on the install instructions.

**Comment by andrewcodes** [comment]
@karlisk thanks for attempting to help. Found out it was a problem with my work's internet filter - they're blocking *.spotify.com.
