### ISSUE TITLE
Can you help me ?

### ISSUE THREAD

**Issue by liberodark** [solus-project/3rd-party#307]
Hello,

I wanted to solicit your help to put my applications on Solus!
Even if only if github.
But I would like to know if you can do a check up of my software and their dependencies?

I do not necessarily want to put on your github even mine can suffice here only I need a little help and saw that I was banned from solus for proposing applications quite viable.I want to maintain my applications on my side.

cordially

**Comment by ikeydoherty** [comment]
Hi - what application? We don't put new stuff in 3rd-party anymore, so proprietary stuff should be snap or flatpak. If its open source and eligible for inclusion in the repos that would be the simplest approach,
having them available directly as binary eopkgs. :)

**Comment by liberodark** [comment]
Actualy use this applications : 

Cudatext 
SmartGit
OnlyOffice
R-Studio
Open-Jardin
Frostwire
Brackets
BlueGriffon
ODrive
Teamviewer 11
Quick n Easy Web Builder 5
 is Done !

**Comment by ikeydoherty** [comment]
Sorry from the way you were wording it you were adding applications you've written. I'm gonna go out on a limb here and say none of those are your apps. If they're distributable and meet eligibility requirements, they can go in the main repositories. Otherwise, the recommended option here is snaps. Note you've duplicated some apps we already have.

**Comment by liberodark** [comment]
ODrive is my application have written this application.
But no have help for solus users ?
This app not have snap just bracket and i not love snap better flatpak.
Have no possibility to help me for port this applications just for now ?
and later go to snap

**Comment by ikeydoherty** [comment]
Like I said if they're distributable and eligible for inclusion they can go into the **main** repositories. This github project is for stuff we **cannot** distribute, and no longer accepts no packages.

From what I can see you originally created an [issue](https://dev.solus-project.com/T4669) on the right place, but you never provided further information to @JoshStrobl. The Solus package policy will not permit web wrappers **unless** they add extra value, such as Discord making use of the global push-to-talk + mics. If you can provide him with that information, then we can satisfy the inclusion policy so that we know its not "just" a web wrapper, and then we could put it straight into the repos **for you**. We just need those details :)

**Comment by JoshStrobl** [comment]
@ikeydoherty Libero was disabled on Phabricator some time ago for actively disrupting tasks. Additionally, their software didn't meet the Value Add portion of our policy, and thus wasn't accepted, which they did not particularly take kindly to and began being hostile and disrupting and necroing tasks in this repo (3rd-party).
